import {useState,useEffect,useRef,useId,Children,cloneElement,isValidElement,type ReactNode,type ReactElement} from 'react';
import {X,Plus,Trash2,Save,SlidersHorizontal,Network,FolderOpen,Users,Search,Settings2,Check,ChevronRight} from 'lucide-react';
import {api,type RecordData} from './api';

export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current!;dialog.showModal();return()=>{dialog.close();};},[]);
  return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
export function Field({label,help,children}:{label:string;help?:string;children:ReactNode}){
  const id=useId();
  const labelled=(nodes:ReactNode):ReactNode=>Children.map(nodes,node=>{
    if(!isValidElement(node))return node;
    const element=node as ReactElement<Record<string,any>>;
    if(['input','select','textarea'].includes(String(element.type)))return cloneElement(element,{'aria-labelledby':id});
    return element.props.children?cloneElement(element,{},labelled(element.props.children)):element;
  });
  return <div className="field"><span id={id}>{label}</span>{labelled(children)}{help&&<small>{help}</small>}</div>;
}
export function WorkspacePicker({value,onSelect,onClose}:{value:string;onSelect:(p:string)=>void;onClose:()=>void}){
  const [current,setCurrent]=useState(value),[listing,setListing]=useState<RecordData>({}),[error,setError]=useState('');
  async function browse(p:string){setCurrent(p);try{setListing(await api(`/browse?path=${encodeURIComponent(p)}`));setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{api('/browse').then(setListing).catch(e=>setError(e.message));},[]);
  return <Modal title="选择任务工作区" onClose={onClose}><div className="modal-body"><p className="muted">每个任务使用独立快照，审核通过后才发布到此目录。可选择 D / E / G 盘已配置路径。</p><Field label="目录路径或别名"><div className="inline"><input value={current} onChange={e=>setCurrent(e.target.value)} placeholder="quant-foundry/项目目录"/><button onClick={()=>browse(current)}>浏览</button></div></Field>{error&&<div className="alert error">{error}</div>}<div className="directory-list">{listing.roots?.map((r:RecordData)=><button key={r.alias} onClick={()=>browse(r.path)}><FolderOpen size={18}/><span>{r.alias}<small>{r.path}</small></span><ChevronRight size={16}/></button>)}{listing.parent&&<button onClick={()=>browse(listing.parent)}>↑ 上级目录</button>}{listing.entries?.map((e:RecordData)=><button key={e.path} onClick={()=>browse(e.path)}><FolderOpen size={18}/>{e.name}<ChevronRight size={16}/></button>)}</div></div><div className="modal-foot"><button onClick={onClose}>取消</button><button className="primary" onClick={()=>{onSelect(current);}}>使用此目录</button></div></Modal>;
}
const panels=[['general','任务与外观',SlidersHorizontal],['models','模型连接',Network],['roles','岗位与预设',Users],['roots','工作区',FolderOpen],['research','资料获取',Search],['context','上下文与记忆',SlidersHorizontal],['advanced','运行与恢复',Settings2]] as const;
export function Settings({initial,onSave,onClose}:{initial:RecordData;onSave:(s:RecordData)=>void;onClose:()=>void}){
  const [s,setS]=useState<RecordData>(()=>structuredClone(initial)),[panel,setPanel]=useState('general'),[keys,setKeys]=useState<RecordData>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[presetName,setPresetName]=useState('');
  const update=(name:string,value:unknown)=>setS(p=>({...p,[name]:value}));
  const [connections,setConnections]=useState<RecordData[]>([]),[checking,setChecking]=useState(false);
  const model=(role:string,key:string,value:unknown)=>setS(p=>({...p,models:{...p.models,[role]:{...p.models[role],[key]:value}}}));
  async function save(){setBusy(true);setError('');try{const saved=await api('/settings','PUT',s);if(Object.values(keys).some(Boolean)){const result=await api('/credentials','PUT',keys);saved.credentialStatus={...saved.credentialStatus,...result.credentialStatus};}onSave(saved);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const number=(name:string,label:string,help?:string,min=1,max?:number)=><Field key={name} label={label} help={help}><input type="number" min={min} max={max} value={s[name]} onChange={e=>update(name,Number(e.target.value))}/></Field>;
  function roleUpdate(index:number,key:string,value:unknown){update('roles',s.roles.map((r:RecordData,i:number)=>i===index?{...r,[key]:value}:r));}
  return <Modal title="设置" onClose={onClose} wide><div className="settings-layout"><nav className="settings-nav">{panels.map(([id,label,Icon])=><button key={id} className={panel===id?'selected':''} onClick={()=>setPanel(id)}><Icon size={18}/>{label}</button>)}<p>设置对新任务生效。<br/>运行中的预算可单独调整。</p></nav><div className="settings-content">
    {panel==='general'&&<><div className="section-title"><h3>少一点管理，多一点完成。</h3><p>只设置一个任务预算，所有席位共同按真实用量结算。</p></div>{number('budgetTokens','默认任务预算（token）','没有请求预留、角色配额或冻结。触达预算后不再发新请求；已发出的并发请求仍会结算，可能超出预算。')}<div className="form-grid"><Field label="主题"><select value={s.theme} onChange={e=>update('theme',e.target.value)}><option value="dark">深色 · 墨绿</option><option value="light">浅色 · 纸白</option><option value="system">跟随系统</option></select></Field>{number('port','本地服务端口','修改端口后重新启动应用。',1024,65535)}</div><div className="info-card"><Check size={22}/><div><strong>会话与任务属于本地服务</strong><p>关闭页面不会删除它们。重新打开可查看同一份对话、图状态和实际回执。</p></div></div></>}
    {panel==='models'&&<><div className="section-title"><h3>异构模型集群</h3><p>固定三席位分工。凭据只存于本机，保存后不会返回浏览器。</p></div>{(['principal','executor','auxiliary'] as const).map((role,index)=><section className="model-card" key={role}><h4><span className={`seat-badge seat-${index}`}>{index+1}</span>{['主席位 · 深度规划与仲裁','执行席位 · 高并发工作','辅助席位 · 独立审核与快响应'][index]}<span className="status-chip">{s.credentialStatus?.[role]?'已配置凭据':'尚未配置'}</span></h4><div className="form-grid"><Field label="模型 ID"><input value={s.models[role].model} onChange={e=>model(role,'model',e.target.value)}/></Field><Field label="协议"><select value={s.models[role].api} onChange={e=>model(role,'api',e.target.value)}><option value="openai-responses">OpenAI Responses</option><option value="openai-completions">OpenAI Chat Completions</option></select></Field></div><Field label="API 基址"><input value={s.models[role].baseUrl} onChange={e=>model(role,'baseUrl',e.target.value)}/></Field><Field label="API Key" help="留空表示保持现有凭据；不会在界面读取或展示已保存的密钥。"><input type="password" autoComplete="new-password" value={keys[role]||''} onChange={e=>setKeys({...keys,[role]:e.target.value})} placeholder="保持现有凭据"/></Field><div className="form-grid three"><Field label="并发席位"><input type="number" min={role==='executor'?10:1} max={role==='principal'?1:role==='auxiliary'?8:20} value={s.models[role].concurrency} onChange={e=>model(role,'concurrency',Number(e.target.value))}/></Field><Field label="推理级别"><select value={s.models[role].thinking} onChange={e=>model(role,'thinking',e.target.value)}>{['off','minimal','low','medium','high','xhigh','max'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="请求超时（秒）"><input type="number" value={s.models[role].requestTimeoutSeconds} onChange={e=>model(role,'requestTimeoutSeconds',Number(e.target.value))}/></Field></div><div className="form-grid"><Field label="上下文窗口（token）"><input type="number" value={s.models[role].contextWindow} onChange={e=>model(role,'contextWindow',Number(e.target.value))}/></Field><Field label="单次最大输出（token）"><input type="number" value={s.models[role].maxOutputTokens} onChange={e=>model(role,'maxOutputTokens',Number(e.target.value))}/></Field></div></section>)}</>}
    {panel==='roles'&&<><div className="section-title"><h3>为任务配一支合适的队伍</h3><p>岗位数量决定各类工作可用席位。执行席位合计须为 10–20；辅助席位 1–8 独立审核，不占执行岗位。</p></div><div className="preset-row">{s.presets.map((p:RecordData)=><div className="preset" key={p.id}><button onClick={()=>{update('roles',structuredClone(p.roles));setS(old=>({...old,roles:structuredClone(p.roles),activePreset:p.id,models:{...old.models,executor:{...old.models.executor,concurrency:p.executor},auxiliary:{...old.models.auxiliary,concurrency:p.auxiliary}}}));}}><Users size={17}/><strong>{p.name}</strong><small>{p.executor} 执行 / {p.auxiliary} 辅助</small></button><button className="icon-button" aria-label={`删除预设 ${p.name}`} onClick={()=>update('presets',s.presets.filter((x:RecordData)=>x.id!==p.id))}><Trash2 size={14}/></button></div>)}</div><div className="inline"><input aria-label="新预设名称" value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="为当前配置命名，例如：模块开发 + 测试"/><button onClick={()=>{if(!presetName.trim())return;update('presets',[...s.presets,{id:crypto.randomUUID(),name:presetName.trim(),executor:s.models.executor.concurrency,auxiliary:s.models.auxiliary.concurrency,roles:structuredClone(s.roles)}]);setPresetName('');}}><Plus size={16}/>保存预设</button></div><div className="allocation">已分配 <strong>{s.roles.reduce((n:number,r:RecordData)=>n+r.count,0)}</strong> / {s.models.executor.concurrency} 个执行席位</div>{s.roles.map((r:RecordData,i:number)=><div className="role-card" key={i}><div className="form-grid role-line"><Field label="岗位名称"><input value={r.name} onChange={e=>roleUpdate(i,'name',e.target.value)}/></Field><Field label="人数"><input type="number" min="0" max="20" value={r.count} onChange={e=>roleUpdate(i,'count',Number(e.target.value))}/></Field><button className="icon-button" aria-label={`删除岗位 ${r.name}`} onClick={()=>update('roles',s.roles.filter((_r:RecordData,n:number)=>n!==i))}><Trash2 size={17}/></button></div><Field label="职责与要求"><textarea rows={3} value={r.instructions} onChange={e=>roleUpdate(i,'instructions',e.target.value)}/></Field></div>)}<button onClick={()=>update('roles',[...s.roles,{name:'新岗位',count:0,instructions:''}])}><Plus size={16}/>添加岗位</button></>}
    {panel==='roots'&&<><div className="section-title"><h3>工作目录，不再藏在 JSON 中</h3><p>使用别名选择跨磁盘工作区。只有已审产物能从独立工作树发布回来。</p></div><Field label="默认任务工作区"><input value={s.defaultWorkspace} onChange={e=>update('defaultWorkspace',e.target.value)}/></Field>{s.roots.map((r:RecordData,i:number)=><div className="root-row" key={i}><Field label="别名"><input value={r.alias} onChange={e=>update('roots',s.roots.map((v:RecordData,n:number)=>n===i?{...v,alias:e.target.value}:v))}/></Field><Field label="本机目录"><input value={r.path} onChange={e=>update('roots',s.roots.map((v:RecordData,n:number)=>n===i?{...v,path:e.target.value}:v))}/></Field><button className="icon-button" aria-label={`删除根目录 ${r.alias}`} onClick={()=>update('roots',s.roots.filter((_r:RecordData,n:number)=>n!==i))}><Trash2 size={16}/></button></div>)}<button onClick={()=>update('roots',[...s.roots,{alias:'new-root',path:'D:\\Code'}])}><Plus size={16}/>添加工作根目录</button><Field label="快照排除目录（每行一个）" help="依赖目录不共享给写入者。需要时在独立工作树安装，避免并发踩踏。"><textarea rows={7} value={s.excludeDirectories.join('\n')} onChange={e=>update('excludeDirectories',e.target.value.split('\n').filter(Boolean))}/></Field></>}
    {panel==='research'&&<><div className="section-title"><h3>信息获取是一等能力</h3><p>检索与原文读取保存来源、时间和内容哈希。网页内容不能覆盖用户指令。</p></div><label className="toggle-row"><input type="checkbox" checked={s.research.enabled} onChange={e=>update('research',{...s.research,enabled:e.target.checked})}/><span>允许公开资料检索与原始来源读取</span></label><Field label="Exa MCP 服务地址"><input value={s.research.mcpUrl} onChange={e=>update('research',{...s.research,mcpUrl:e.target.value})}/></Field><Field label="检索 API Key（可选）"><input type="password" autoComplete="new-password" placeholder="留空保持现有设置；公共端点可免密" value={keys.research||''} onChange={e=>setKeys({...keys,research:e.target.value})}/></Field><Field label="浏览器检索地址模板"><input value={s.research.searchUrl} onChange={e=>update('research',{...s.research,searchUrl:e.target.value})}/></Field><div className="form-grid"><Field label="来源读取超时（秒）"><input type="number" value={s.research.fetchTimeoutSeconds} onChange={e=>update('research',{...s.research,fetchTimeoutSeconds:Number(e.target.value)})}/></Field><Field label="单来源最大字节数"><input type="number" value={s.research.maxSourceBytes} onChange={e=>update('research',{...s.research,maxSourceBytes:Number(e.target.value)})}/></Field></div><div className="info-card"><Search size={22}/><p>优先原始论文、官方资料和版本对应源码。检索失败会保留错误，PDF 未解析时不会伪称已读。</p></div></>}
    {panel==='advanced'&&<><div className="section-title"><h3>运行边界与恢复</h3><p>限制用于结束失控循环，不参与预算预留。所有失败都有明确状态。</p></div><div className="form-grid">{number('maxRepairRounds','自动返工轮数','岗位与整体任务均受此上限约束。',0,8)}{number('maxAgentTurns','单岗位最大工具轮数',undefined,1,1000)}{number('commandTimeoutSeconds','原生命令超时（秒）')}{number('pythonStartupSeconds','Python 启动超时（秒）')}{number('pythonCellTimeoutSeconds','Python 单元执行超时（秒）')}{number('snapshotMaxMiB','快照上限（MiB）')}{number('snapshotMaxFiles','快照文件数量上限')}</div><Field label="始终运行的验证命令（每行一条 PowerShell 命令）"><textarea rows={5} value={s.verificationCommands.join('\n')} onChange={e=>update('verificationCommands',e.target.value.split('\n').filter(Boolean))}/></Field><label className="toggle-row"><input type="checkbox" checked={s.autoResume} onChange={e=>update('autoResume',e.target.checked)}/><span>服务重启后恢复可安全重试的节点</span></label><p className="muted">原生命令结果未知时不自动重放；会话和产物仍保留。工作树防并发误写不是操作系统安全沙箱，运行本机代码拥有当前用户权限。</p></>}
    {panel==='advanced'&&<Field label="可再生构建输出目录（每行一个相对目录）" help="仅新生成、未被岗位声明为交付物的文件可作临时输出。原先已有文件的修改仍受源码完整性检查；此项不同于快照排除目录。"><textarea rows={5} value={(s.generatedDirectories||[]).join('\n')} onChange={e=>update('generatedDirectories',e.target.value.split('\n').filter(Boolean))}/></Field>}
    {panel==='models'&&<div className="connection-check"><button disabled={checking} onClick={async()=>{setChecking(true);try{const result=await api('/connections/check','POST',{});setConnections(result.connections);}catch(e){setError((e as Error).message);}finally{setChecking(false);}}}>{checking?'检查中…':'检查已保存端点的可达性'}</button><p className="muted">不消耗模型 token。TCP 可达不等于 API 认证或真实模型调用通过；先保存设置再检查。</p>{connections.map(c=><div className={`alert ${c.ok?'':'error'}`} key={c.role}><strong>{c.role} · {c.ok?'TCP 可达':c.code}</strong><p>{c.endpoint} · {c.latencyMs} ms</p></div>)}</div>}
    {panel==='context'&&<><div className="section-title"><h3>压缩上下文，不丢掉原始证据</h3><p>采用 Pi 原生摘要和工具调用边界。完整轨迹保存在本地，模型可以按需回读；摘要不能替代审核证据。</p></div><label className="toggle-row"><input type="checkbox" checked={s.context.enabled} onChange={e=>update('context',{...s.context,enabled:e.target.checked})}/><span>按上下文压力自动压缩</span></label><Field label="触发比例" help="相对于模型上下文窗口的估算比例；不是预算预留。"><input type="number" min="0.25" max="0.9" step="0.05" value={s.context.triggerRatio} onChange={e=>update('context',{...s.context,triggerRatio:Number(e.target.value)})}/></Field><div className="form-grid"><Field label="保留近期上下文（token）"><input type="number" min="1024" max="65536" value={s.context.keepRecentTokens} onChange={e=>update('context',{...s.context,keepRecentTokens:Number(e.target.value)})}/></Field><Field label="摘要最大输出（token）"><input type="number" min="1024" max="16384" value={s.context.summaryMaxTokens} onChange={e=>update('context',{...s.context,summaryMaxTokens:Number(e.target.value)})}/></Field></div><p className="muted">摘要调用同样按提供方实际用量记入该任务的唯一预算。关闭压缩后，大上下文仍受模型服务限制；不会悄悄截掉早期消息后宣称完整。</p></>}
  </div></div>{error&&<div className="settings-error alert error" role="alert">{error}</div>}<div className="modal-foot"><span className="muted">本地保存 · 不需要环境变量</span><button onClick={onClose}>取消</button><button className="primary" disabled={busy} onClick={save}><Save size={17}/>{busy?'保存中…':'保存设置'}</button></div></Modal>;
}
